version: '3.1'

services:
  postgres:
    image: postgres:11.6
    restart: always
    environment:
      - POSTGRES_DB=ggrab_service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456789
    volumes:
      - ./mock-db:/var/lib/postgresql
    ports:
      - "5430:5432"

  rabbitmq-ph-auth:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    volumes:
      - /mock-rabbitmq:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@admin.com
      - PGADMIN_DEFAULT_PASSWORD=123456789
    ports:
      - "5050:80"